export const FETCH_SKILLS_INIT = 'FETCH_SKILLS_INIT';
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS';
export const FETCH_SKILLS_ERROR = 'FETCH_SKILLS_ERROR';

export const ADD_SKILL = 'ADD_SKILL';

export const SELECTION_EXPERIENCE = 'SELECTION_EXPERIENCE';

export const CREATE_SKILL_INIT = 'CREATE_SKILL_INIT';
export const CREATE_SKILL_SUCCESS = 'CREATE_SKILL_SUCCESS';
export const CREATE_SKILL_ERROR = 'CREATE_SKILL_ERROR';

export const DELETE_SKILL_INIT = 'DELETE_SKILL_INIT';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_ERROR = 'DELETE_SKILL_ERROR';